### ISSUE TITLE
Indexing into a related manager's queryset fails

### ISSUE THREAD

**Issue by fish-face** [charettes/django-seal#42]
```patch
diff --git a/tests/test_query.py b/tests/test_query.py
index d5dfef2..7b0fb8e 100644
--- a/tests/test_query.py
+++ b/tests/test_query.py
@@ -252,6 +252,8 @@ class SealableQuerySetTests(TestCase):
         message = 'Attempt to fetch many-to-many field "visitors" on sealed <Location instance>'
         with self.assertRaisesMessage(UnsealedAttributeAccess, message):
             list(instance.visitors.all())
+        with self.assertRaisesMessage(UnsealedAttributeAccess, message):
+            instance.visitors.all()[0]
 
     def test_not_sealed_reverse_foreign_key(self):
         instance = Location.objects.get()
```

```pytb
ERROR: test_sealed_reverse_foreign_key (tests.test_query.SealableQuerySetTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_query.py", line 256, in test_sealed_reverse_foreign_key
    instance.visitors.all()[0]
  File "/home/fish/Documents/programming/django-seal/.tox/py27-1.11/lib/python2.7/site-packages/django/db/models/query.py", line 289, in __getitem__
    return list(qs)[0]
  File "/home/fish/Documents/programming/django-seal/.tox/py27-1.11/lib/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "seal/descriptors.py", line 43, in _fetch_all
    warnings.warn(self._sealed_warning, category=UnsealedAttributeAccess, stacklevel=3)
AttributeError: 'SealedRelatedQuerySet' object has no attribute '_sealed_warning'
```

I believe this is because `__getitem__` clones the queryset in order to apply a `limit` for the index. I haven't fully understood what goes on, but to save you a bit of time I did notice that when we get to `clone`, `self.__class__.__mro__` starts 
```python3
(seal.descriptors.SealedSealableQuerySet, descriptors.SealedRelatedQuerySet, query.SealableQuerySet, ...)
```

So the line which strips off the outermost sealed queryset leaves you with another sealed queryset. I guess the fault lies in the code which is constructing the queryset class because it should see that the class is already sealed and not try to seal it again.

While looking into this issue I noticed that `SealableQueryset` defines `sealed = False` but `SealedRelatedQuerySet` does not override this. Nothing seems to use this parameter.

**Comment by charettes** [comment]
Thanks for the report, addressed the issue and [released 1.2.0](https://pypi.org/project/django-seal/)
