### ISSUE TITLE
Empty `select_related` raises AttributeError

### ISSUE THREAD

**Issue by JiriKr** [charettes/django-seal#80]
Hi, thanks for this great tool.

Yes, I know, it's not a good practise to use `select_related()`, but we have existing project and decided to integrate django-seal. I would say it would be better to warn instead of failure.

Example:
```python
from django.db import models
from seal.models import SealableModel


class Author(SealableModel):
    name = models.CharField(max_length=100)


class Book(SealableModel):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

$ Book.objects.seal().select_related("author").first().author
<Author: Author object (1)>

$ Book.objects.seal().select_related().first().author
Traceback (most recent call last):
  File "/home/django/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-5170006a92d9>", line 1, in <module>
    Book.objects.seal().select_related().first().author
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/django/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1097, in first
    for obj in queryset[:1]:
               ~~~~~~~~^^^^
  File "/home/django/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 400, in __iter__
    self._fetch_all()
  File "/home/django/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/django/.venv/lib/python3.12/site-packages/seal/query.py", line 50, in __iter__
    select_related_getters = tuple(
                             ^^^^^^
  File "/home/django/.venv/lib/python3.12/site-packages/seal/query.py", line 11, in get_select_related_getters
    for lookup, nested_lookups in lookups.items():
                                  ^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'items'
```

Python version: 3.12.5
Django version: 5.0.8
django-seal version: 1.6.2

**Comment by charettes** [comment]
@JiriKr thanks for the report. Could you confirm that #81 addresses your issue?

**Comment by JiriKr** [comment]
Yes, it works. Thank you.

**Comment by charettes** [comment]
Great I'll release 1.6.3 with the changes included.
